### ISSUE TITLE
Add complete list of AR codes to website

### ISSUE THREAD

**Issue by mm201** [mm201/pkmn-classic-framework#11]
I really want to have a page where you select your version and language and it displays the corresponding NoSSL AR code you need, but I don't have access to all the different versions. (Don't suggest piracy.)

So I'm requesting help. I need to compile a list of NoSSL codes for all supported games (Diamond, Pearl, Platinum, Heart Gold, Soul Silver, Black, White, Black 2, White 2) in each of the following languages:
- [ ] Japanese
- [x] English (NA)
- [ ] English (EU)
- [ ] French
- [ ] Italian
- [ ] German
- [ ] Spanish
- [ ] Korean

**Comment by arttu97** [comment]
Pokemon White (EU) 

520882EC EE070F90
E2004354 0000007A
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE925 000A002C
00A70009 D2ED004D
000DA191 00190011
001A001A 001A001A
001B001B 00050505
23E72F3C 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
020882EC E92D401E
020882F0 FAFDF017
D2000000 00000000

**Comment by arttu97** [comment]
Pokemon Diamond (USA) (ADAE)

520CD848 EE070F90
E2000674 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB88
D2000000 00000000

**Comment by pkmntrainerryan** [comment]
diamond:
520CD848 EE070F90
E2000674 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB88
D2000000 00000000

pearl:
520CD848 EE070F90
E2000630 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB77
D2000000 00000000


platinum:
520C42BC EE070F90
E20001C8 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2244D 015E0012
0382004D 0009000A
0005000B 00000000
020C42BC E92D401E
020C42C0 FAFCEFC0
D2000000 00000000

soul silver:
520D3F5C EE070F90
E20001DC 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229CD 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB09D
D2000000 00000000

heart gold:

520D3F5C EE070F90
E2000010 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229CD 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB02A
D2000000 00000000

white:
520882EC EE070F90
E2004354 0000007A
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE925 000A002C
00A70009 D2ED004D
000DA191 00190011
001A001A 001A001A
001B001B 00050505
23E72F3C 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
020882EC E92D401E
020882F0 FAFDF017
D2000000 00000000

black:
520882D4 EE070F90
E2004720 0000007A
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE905 000A002C
00A70009 D2ED004D
000DA171 00190011
001A001A 001A001A
001B001B 00050505
23E72F3C 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
020882D4 E92D401E
020882D8 FAFDF110
D2000000 00000000

white 2:
5207C818 EE070F90
E200477C 0000007C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E920D9 000A002C
00A70009 D2EB004D
000D8E0D 00190011
001A0019 001A001A
001B001A 052A001B
4AAF0005 00160164
00160013 001501BE
00130012 00120014
0000001D 00000000
0207C818 E92D401E
0207C81C FAFE1FD6
D2000000 00000000

black2:
5207C7EC EE070F90
E20044FC 0000007C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E92099 000A002C
00A70009 D2EB004D
000D8DCD 00190011
001A0019 001A001A
001B001A 052A001B
4AAF0005 00160164
00160013 001501BE
00130012 00120014
0000001D 00000000
0207C7EC E92D401E
0207C7F0 FAFE1F41
D2000000 00000000

**Comment by PokeAcer549** [comment]
^^ NTSC or PAL (America Or EU)?

**Comment by pkmntrainerryan** [comment]
those are for the us games

**Comment by the4anoni** [comment]
Here I post all codes for Pokemon Diamont :
-J
520CF9F8 EE070F90
E2000010 0000004C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F19921 0070014B
000A0327 000D0009
00000005 00000000
020CF9F8 E92D401E
020CF9FC FAFCC183
D2000000 00000000
-Eu
520CD848 EE070F90
E2000674 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB88
D2000000 00000000
-Fr
520CD8A4 EE070F90
E20001F8 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F185E1 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCCA52
D2000000 00000000
-Ger
520CD8A4 EE070F90
E2000248 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F185A1 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCCA66
D2000000 00000000
-Es
520CD8A4 EE070F90
E2000230 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18601 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCCA60
D2000000 00000000
-Ks
520C9E88 EE070F90
E200007C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F173E1 015E0012
0382004D 0009000A
0005000B 00000000
020C9E88 E92D401E
020C9E8C FAFCD87A
D2000000 00000000
-Usa
520CD848 EE070F90
E2000674 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB88
D2000000 00000000
-It
520CD884 EE070F90
E20000C8 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18541 01200035
03270070 0009000A
0005000D 00000000
020CD884 E92D401E
020CD888 FAFCCA0E
D2000000 00000000

If I will have more time I will post codes for all Pokemon Games :)

**Comment by PokeAcer549** [comment]
I see you posted German, French, Italian and European. 
Just saying, EU have the exact same cart for all.

**Comment by Link2738** [comment]
Pokemon Diamond (jap)
520CF9F8 EE070F90
E2000010 0000004C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F19921 0070014B
000A0327 000D0009
00000005 00000000
020CF9F8 E92D401E
020CF9FC FAFCC183
D2000000 00000000

Pokemon Pearl Jap
520CFB3C EE070F90
E2000344 0000004C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F19A61 0070014B
000A0327 000D0009
00000005 00000000
020CFB3C E92D401E
020CFB40 FAFCC1FF
D2000000 00000000

Pokemon Platinum Jap
520C3A4C EE070F90
E20001A0 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2184D 015E0012
0382004D 0009000A
0005000B 00000000
020C3A4C E92D401E
020C3A50 FAFCF1D2
D2000000 00000000

Pokemon Soulsilver Jap
520D37D4 EE070F90
E20000E4 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F21F0D 015E0012
0382004D 0009000A
0005000B 00000000
020D37D4 E92D401E
020D37D8 FAFCB241
D2000000 00000000

**Comment by Link2738** [comment]
Pokemon Soul Silver Jap
520D37D4 EE070F90
E200063C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F21F0D 015E0012
0382004D 0009000A
0005000B 00000000
020D37D4 E92D401E
020D37D8 FAFCB397
D2000000 00000000

Pokemon Black Jap
520881E0 EE070F90
E2004450 00000076
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE771 000A002C
00A70009 D2ED004D
001DA03D 00190019
00190019 001A0019
00050522 24372F35
00130016 01BE0016
00120015 00140013
001D0012 00000000
020881E0 E92D401E
020881E4 FAFDF099
D2000000 00000000

Pokemon White Jap
520881F8 EE070F90
E2004780 00000076
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE791 000A002C
00A70009 D2ED004D
001DA05D 00190019
00190019 001A0019
00050522 24372F35
00130016 01BE0016
00120015 00140013
001D0012 00000000
020881F8 E92D401E
020881FC FAFDF15F
D2000000 00000000

Pokwmon White2 Jap
5207C4F8 EE070F90
E2004378 0000007A
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E91A99 000A002C
00A70009 D2EB004D
001D87CD 00190018
00190019 00190019
001A001A 0005052A
01644AAF 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
0207C4F8 E92D401E
0207C4FC FAFE1F9D
D2000000 00000000

Pokemon Black2 Jap Code not loading

**Comment by Link2738** [comment]
The Second Soul silver is a typo It's Heart gold Jap Sorry

**Comment by the4anoni** [comment]
Pokemon Pearl NoSsl Codes :)
-Eu
520CD848 EE070F90
E2000630 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18461 01200035
03270070 0009000A
0005000D 00000000
020CD848 E92D401E
020CD84C FAFCCB77
D2000000 00000000
-Es
520CD8A4 EE070F90
E2000074 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18601 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCC9F1
D2000000 00000000
-De
520CD8A4 EE070F90
E2000070 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F185A1 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCC9F0
D2000000 00000000
-Ks
520C9E88 EE070F90
E200045C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F173E1 015E0012
0382004D 0009000A
0005000B 00000000
020C9E88 E92D401E
020C9E8C FAFCD972
D2000000 00000000
-Fr
520CD8A4 EE070F90
E200046C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F185E1 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCCAEF
D2000000 00000000
-It
520CD884 EE070F90
E2000510 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18541 01200035
03270070 0009000A
0005000D 00000000
020CD884 E92D401E
020CD888 FAFCCB20
D2000000 00000000

Please report codes that working.

**Comment by the4anoni** [comment]
Platinum NoSsl Codes
-Eu
520C42BC EE070F90
E20001C8 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2244D 015E0012
0382004D 0009000A
0005000B 00000000
020C42BC E92D401E
020C42C0 FAFCEFC0
D2000000 00000000
-Fr
520C4360 EE070F90
E2000248 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2262D 015E0012
0382004D 0009000A
0005000B 00000000
020C4360 E92D401E
020C4364 FAFCEFB7
D2000000 00000000
-De
520C4360 EE070F90
E2000010 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F225ED 015E0012
0382004D 0009000A
0005000B 00000000
020C4360 E92D401E
020C4364 FAFCEF29
D2000000 00000000
-It
520C4360 EE070F90
E20006A4 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F225AD 015E0012
0382004D 0009000A
0005000B 00000000
020C4360 E92D401E
020C4364 FAFCF0CE
D2000000 00000000
-Es
520C4360 EE070F90
E2000644 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2264D 015E0012
0382004D 0009000A
0005000B 00000000
020C4360 E92D401E
020C4364 FAFCF0B6
D2000000 00000000
-Ks
520C4D8C EE070F90
E200041C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2334D 015E0012
0382004D 0009000A
0005000B 00000000
020C4D8C E92D401E
020C4D90 FAFCEDA1
D2000000 00000000

**Comment by the4anoni** [comment]
Special !!!
Pokemon Black 2 Japan code !!!
5207C4CC EE070F90
E2004310 0000003C
CA024A0D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
020044C8 00000000
E20044C8 00000042
D2E91A79 000A002C
00A70009 D2EB004D
001D87AD 00190018
00190019 00190019
001A001A 0005052A
01644AAF 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
0207C4CC E92D401E
0207C4D0 FAFE1F8E
D2000000 00000000
Thanks to prof.9 for generate code for me :)

**Comment by mm201** [comment]
Thanks everyone! I'll get these onto the new instructions page once it's ready.

**Comment by the4anoni** [comment]
Pokemon Heartgold Es NoSsl Code
520D3F54 EE070F90
E200043C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229ED 015E0012
0382004D 0009000A
0005000B 00000000
020D3F54 E92D401E
020D3F58 FAFCB137
D2000000 00000000
Ps.Generated via WfcReplay v0.6
Ps.2.I can made cheat database when we have all codes. But at this moment only in .dat format ...

**Comment by the4anoni** [comment]
Pokemon HeartGold:
-Eu
 520D3F5C EE070F90
E2000010 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229CD 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB02A
D2000000 00000000

**Comment by the4anoni** [comment]
-Fr
 520D3F5C EE070F90
E2000440 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229ED 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB136
D2000000 00000000

**Comment by the4anoni** [comment]
-Italiano 
 520D3F5C EE070F90
E20000F4 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2296D 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB063
D2000000 00000000

**Comment by the4anoni** [comment]
-Ks
 520D4650 EE070F90
E2000084 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F233CD 015E0012
0382004D 0009000A
0005000B 00000000
020D4650 E92D401E
020D4654 FAFCAE8A
D2000000 00000000

**Comment by the4anoni** [comment]
-Ger
 520D3F5C EE070F90
E20006A4 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229AD 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB1CF
D2000000 00000000

**Comment by henias** [comment]
Hmmm, maybe someone has White 2 EUR code?

**Comment by vigneshd332** [comment]
Hmmm guys. Sorry if i disturbed, but i dont use AR codes ro cheat in pokemon black ,platinum and soulsilver. I use Pokegen a software from project pokemon.org. It will generate codes for what you want. Happy to help. Works on heart gold, white , blk2 and wht2. Havent tried it on doamond amd pearl.

**Comment by PokeAcer549** [comment]
This is not the point of this thread. This thread helps share NoSSL codes for Pokemon Games.

**Comment by the4anoni** [comment]
Created list of which codes we need ,but someone must check is it correct [![Przechwytywanie.png](https://s28.postimg.org/umfr4y7nx/Przechwytywanie.png)](https://postimg.org/image/nj7vpc289/)

**Comment by vigneshd332** [comment]
Hey buddy in which version of wfc replay should we try thing white 2 eur thingy

**Comment by vigneshd332** [comment]
::Bypass HTTPS v0.6 for [IPGE] POKEMON SS
520D3F5C EE070F90
E20001DC 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229CD 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB09D
D2000000 00000000

**Comment by Link2738** [comment]
Region of game?

**Comment by Link2738** [comment]
I've compiled the codes onto the altwfc wiki if anyone wants to check it out

**Comment by maylay** [comment]
Updated the list now with the codes that were missing.

**Comment by vigneshd332** [comment]
Someone pls provide links for blk 2 and wht 2 eu roms. So i can upload the ar codes

**Comment by vigneshd332** [comment]
Fast response appreciated.

Posted from Vector Revetron V7 Max running Ubuntu.

**Comment by mm201** [comment]
Don't ask for roms here.

**Comment by xJoelituh** [comment]
Leaving here all the Spanish Codes:

**Pokemon Diamond (S):**
520CD8A4 EE070F90
E2000230 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18601 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCCA60
D2000000 00000000

**Pokemon Pearl (S):**
520CD8A4 EE070F90
E2000074 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F18601 01200035
03270070 0009000A
0005000D 00000000
020CD8A4 E92D401E
020CD8A8 FAFCC9F1
D2000000 00000000

**Pokemon Platinum (S):**
520C4360 EE070F90
E2000644 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F2264D 015E0012
0382004D 0009000A
0005000B 00000000
020C4360 E92D401E
020C4364 FAFCF0B6
D2000000 00000000

**Pokemon Heart Gold (S):**
520D3F54 EE070F90
E200043C 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F229ED 015E0012
0382004D 0009000A
0005000B 00000000
020D3F54 E92D401E
020D3F58 FAFCB137
D2000000 00000000

**Pokemon Soul Silver (S):**
520D3F5C EE070F90
E2000494 0000004E
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2F22A0D 015E0012
0382004D 0009000A
0005000B 00000000
020D3F5C E92D401E
020D3F60 FAFCB14B
D2000000 00000000

**Pokemon Black (S):**
520882A4 EE070F90
E20041A8 0000007A
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE8C5 000A002C
00A70009 D2ED004D
000DA131 00190011
001A001A 001A001A
001B001B 00050505
23E72F3C 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
020882A4 E92D401E
020882A8 FAFDEFBE
D2000000 00000000

**Pokemon Black 2 (S):**
5207C7BC EE070F90
E20045DC 0000007C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E92059 000A002C
00A70009 D2EB004D
000D8D8D 00190011
001A0019 001A001A
001B001A 052A001B
4AAF0005 00160164
00160013 001501BE
00130012 00120014
0000001D 00000000
0207C7BC E92D401E
0207C7C0 FAFE1F85
D2000000 00000000

**Pokemon White (S):**
520882BC EE070F90
E2004458 0000003C
CA024A0D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
02004010 00000000
E2004010 00000042
D2EAE8C5 000A002C
00A70009 D2ED004D
000DA131 00190011
001A001A 001A001A
001B001B 00050505
23E72F3C 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
020882BC E92D401E
020882C0 FAFDF064
D2000000 00000000

**Pokemon White 2 (S):**
5207C7E8 EE070F90
E2004600 0000007C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E92079 000A002C
00A70009 D2EB004D
000D8DAD 00190011
001A0019 001A001A
001B001A 052A001B
4AAF0005 00160164
00160013 001501BE
00130012 00120014
0000001D 00000000
0207C7E8 E92D401E
0207C7EC FAFE1F83
D2000000 00000000

**Comment by Link2738** [comment]
For all EUR countries the EUR version code is all that's needed

**Comment by mm201** [comment]
Reopening this since it's still required for GenV for now.

**Comment by fancymelonub** [comment]
NoSSL codes for Gen 5 (I'll keep updating this post.)
Pocket Monsters Black
520881E0 EE070F90
E2004450 000000A8
CA02A20C 02242303
19645CCD D5FA3B01
42A34B07 784CD104
3101700C D1FA4224
428AA121 4778DBED
EE070F90 E8BD803E
2F2F3A73 021A21E4
021A2294 021A22BC
021A22E0 021A257C
021A26B0 021CDAB0
021CDAE3 021CDB24
021CDB88 021CDBEC
021CDC50 021CDCB4
021CDD18 021CDD80
021CF208 021CF21C
021DAEF0 021E3FCC
021E4024 021E4070
021E40C8 021E47C0
021E4814 021E485C
021E48A8 021E48F8
021E4940 021E49B4
020881E0 E92D403E
020881E4 FAFDF099
D2000000 00000000

Pokèmon Black
520882D4 EE070F90
E2004720 0000007A
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2EAE905 000A002C
00A70009 D2ED004D
000DA171 00190011
001A001A 001A001A
001B001B 00050505
23E72F3C 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
020882D4 E92D401E
020882D8 FAFDF110
D2000000 00000000

**Comment by fancymelonub** [comment]
NoSSL codes for Gen 5 2/2 (I'll keep updating this 'till it's done.)
Pocket Monsters White 2 (JP)
5207C4F8 EE070F90
E2004378 000000B0
CA02A20C 02242303
19645CCD D5FA3B01
42A34B07 784CD104
3101700C D1FA4224
428AA123 4778DBED
EE070F90 E8BD803E
2F2F3A73 0218550C
021855BC 021855E4
02185608 021858A4
021859D8 021AC240
021AC273 021AC2B4
021AC314 021AC378
021AC3DC 021AC440
021AC4A4 021AC508
021AC570 021AC5D8
021ADA80 021ADA94
021C0550 021C0AE0
021C0B38 021C0B84
021C0BDC 021C12D4
021C1328 021C1370
021C13BC 021C140C
021C1454 021C14C8
0207C4F8 E92D403E
0207C4FC FAFE1F9D
D2000000 00000000

Pokèmon White 2 (US)
5207C818 EE070F90
E200477C 0000007C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E920D9 000A002C
00A70009 D2EB004D
000D8E0D 00190011
001A0019 001A001A
001B001A 052A001B
4AAF0005 00160164
00160013 001501BE
00130012 00120014
0000001D 00000000
0207C818 E92D401E
0207C81C FAFE1FD6
D2000000 00000000

Pocket Monsters Black 2 (JP)
5207C4CC EE070F90
E20044C8 000000B0
CA02A20C 02242303
19645CCD D5FA3B01
42A34B07 784CD104
3101700C D1FA4224
428AA123 4778DBED
EE070F90 E8BD803E
2F2F3A73 021854EC
0218559C 021855C4
021855E8 02185884
021859B8 021AC220
021AC253 021AC294
021AC2F4 021AC358
021AC3BC 021AC420
021AC484 021AC4E8
021AC550 021AC5B8
021ADA60 021ADA74
021C0530 021C0AC0
021C0B18 021C0B64
021C0BBC 021C12B4
021C1308 021C1350
021C139C 021C13EC
021C1434 021C14A8
0207C4CC E92D403E
0207C4D0 FAFE1FFC
D2000000 00000000

Pokèmon Black 2 (US)
5207C7EC EE070F90
E20044FC 0000007C
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2E92099 000A002C
00A70009 D2EB004D
000D8DCD 00190011
001A0019 001A001A
001B001A 052A001B
4AAF0005 00160164
00160013 001501BE
00130012 00120014
0000001D 00000000
0207C7EC E92D401E
0207C7F0 FAFE1F41
D2000000 00000000

**Comment by fancymelonub** [comment]
All of the NoSSL code TXTs generated by WFCReplay.
[Codes.zip](https://github.com/mm201/pkmn-classic-framework/files/2592937/Codes.zip)

**Comment by fancymelonub** [comment]
(Are you gonna update the main post?)

**Comment by InternalLoss** [comment]
Is this truly even needed anymore, with the NDS-Constraint system now in place?

**Comment by mm201** [comment]
Yes, because it [doesn't work on GenV](https://github.com/mm201/pkmn-classic-framework/issues/58).

**Comment by fancymelonub** [comment]
@mm201 It does, it works for me. Have you tried using RiiConnect24's DNS (164.132.44.106) for it instead of KaeruTeam's dead DNS?

**Comment by MightyJoeYoung** [comment]
Can back up fancymelonub, I can very easily access most Black*/White* features on RiiConnect24's DNS, but you still need these noSSL AR codes for the GTS. You can search, but not trade.

**Comment by mm201** [comment]
Which means we still need these codes.

**Comment by mm201** [comment]
Thanks for all your work but GenV is now working without codes. I was getting hung up on the web design side of this so that's good too!
