### ISSUE TITLE
Case sensitive Database Table Names under Linux -> inconsistent names 

### ISSUE THREAD

**Issue by Cowboyjunkie** [mm201/pkmn-classic-framework#110]
I noticed that the mariaDB which I use under Pi OS is case sensitive with Table Names.

Library -> Data -> MySQL.cs   3288  "FROM pkmncf_pokedex_pokemon_form_Stats"))

Library -> Data -> MySQL.cs   3014  db.ExecuteNonQuery("INSERT INTO pkmncf_pokedex_pokemon_form_stats " +

Line 3288 is so far the only one I found where the "S" is _stats has a uppercase "S". In all other instances the s is lowercase.

Might not be relevant under Windows (not used MySQL in Windows, but SQL Express is not case sensitive with Table Names.

Regards,
John

**Comment by mm201** [comment]
It's a typo. Neither Windows nor Mac have case-sensitive table names by default, so I never noticed. Should be fixed soon.
