### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by PokeAcer549** [mm201/pkmn-classic-framework#12]
How do you install onto a clean AltWFC server?

**Comment by mm201** [comment]
It doesn't communicate directly with AltWFC. (This is true of all the http gamestats servers.)

To run the GTS, you need a mysql database and an ASP.Net capable web server. I use IIS but I don't see any reason why nginx fastCGI and Apache mod-mono wouldn't work. You'll need to change the database IP address, username, and password in each of the `*.config` files to match your database. Run the included `database.sql` then run the VeekunImport project to build the Pokedex. After that it should just work.

The battle video server should run as a plain old process if the `DEBUG` flag is set.

**Comment by PokeAcer549** [comment]
Thanks, I've done some of this, but I had a few issues:
* VeekunImport crashes with this error > http://prntscr.com/7gw4mk < - Or do I run the files from VS2012?
* bvCrawler4 also crashes > http://prntscr.com/7gw5o9 <
* GTS defaults to port 12400, yet the DS is looking for it on port 80 > http://prntscr.com/7gw60n <
* the ASPX files in web folder make IIS say 'HTTP500'
* MakeBaseStat Tables > http://prntscr.com/7gw6so <

Can you explain step-by-step how to set everything up (from config to running the programs)

**Comment by mm201** [comment]
VeekunImport: You need pokedex.sqlite from http://veekun.com/dex/downloads
Don't bother with the bvCrawler projects. They crawled the now defunct official battle video server and saved videos.
GTServer isn't GTS, it's "Global Terminal" which is battle videos and things like that. It seems to be working perfectly?

Try running the web projects in VS to get more meaningful errors. I'm willing to bet it's the database not being initialized fully.

**Comment by PokeAcer549** [comment]
Thanks! This'll help a lot!
I'll look into the web projects, and post any errors here.

**Comment by PokeAcer549** [comment]
OK. I've tried using GTS (HTTP500 to DS, My IIS says 'XML Parsing Error: no element found;Location: http://IP/Global.aspx;Line Number 1, Column 1: <blank>' - ; = a new line (I added that in) ' when trying to access the main page via IE10 (FF shows up blank) or even the info.asp' Also, considering there's only some files and no folders how does that work?

My BattleVideo server wasnt working either, 106025. 

Packet Capture of all this > https://openwrt.cloudshark.org/captures/3271d7f97ddb <

**Comment by mm201** [comment]
The battle video server isn't working because you don't have a DNS entry for `pkgdsprod.nintendo.co.jp`.
The GTS is a web app and needs to be deployed to a folder from VS. (Build / Publish Web Site)

**Comment by PokeAcer549** [comment]
I was just going to say, I need to do the DNS. And thanks!

**Comment by PokeAcer549** [comment]
Can I run the GTS server and the pkmnclassic website in the same place?
If no, I'll try having the website on :81

**Comment by PokeAcer549** [comment]
Closing, I've done everything.
Thanks a lot @mm201 !

**Comment by PokeAcer549** [comment]
Problem.
I get 404 on my gts when trying to connect to it via Platinum.
https://openwrt.cloudshark.org/captures/f57bdab71cf2
For some reason I used to never get it.

**Comment by mm201** [comment]
Looks like the host `gamestats2.gs.nintendowifi.net` isn't routing to the correct application.

**Comment by PokeAcer549** [comment]
OK.
Also, why does it try to redirect to 12400? Whenever I recompile and put into IIS it enables a redirect.
And how isnt it going to the correct application, it points to my server holding WebServer

**Comment by PokeAcer549** [comment]
Hey @mm201 , I've redone the install, and I've actually done this on mod_mono . However, I believe that Global.asax is the directory listing, so I set it to the directory listing. However, if you go to my server (http://185.99.132.59/pkmn/ in browser, Apache virtualhosts it so http://185.99.132.59 = http://185.99.132.59/pkmn/ for gamestats2.gs.nintendowifi.net) you'll see this:
`System.Web.Compilation.CompilationException
: Unhandled Exception:

Description: Error compiling a resource required to service this request. Review your source file and modify it to fix this error.

Details: : Unhandled Exception:

Error origin: Compiler

Error source file: ~/Global.asax
Exception stack trace:
  at System.Web.Compilation.AssemblyBuilder.BuildAssembly (System.Web.VirtualPath virtualPath, System.CodeDom.Compiler.CompilerParameters options) [0x00000] in <filename unknown>:0 
  at System.Web.Compilation.AssemblyBuilder.BuildAssembly (System.Web.VirtualPath virtualPath) [0x00000] in <filename unknown>:0 
  at System.Web.Compilation.BuildManager.GenerateAssembly (System.Web.Compilation.AssemblyBuilder abuilder, System.Web.Compilation.BuildProviderGroup group, System.Web.VirtualPath vp, Boolean debug) [0x00000] in <filename unknown>:0 
  at System.Web.Compilation.BuildManager.BuildInner (System.Web.VirtualPath vp, Boolean debug) [0x00000] in <filename unknown>:0 `

**Comment by DracoMilesX** [comment]
@PokeAcer549 Just wondering are you able to re-write the wiki on installing the web app and battle server for Linux with mod_mono? Or update the Windows one? Since you state to publish the GTS folder to my web root but then the page remains blank.

**Comment by celorodovalho** [comment]
@DracoMilesX @PokeAcer549 +1 for the last reply above

**Comment by PokeAcer549** [comment]
Sure, but I currently have no time :P

**Comment by ductator** [comment]
Would also appreciate more detailed instructions. My attempts fail at reaching gts, as Internal HTTP error get's returned every time.

**Comment by PokeAcer549** [comment]
Ensure you have ASP.NET correctly configured.
