### ISSUE TITLE
how configure and install

### ISSUE THREAD

**Issue by andromeda01** [mm201/pkmn-classic-framework#14]
i have a vmware vm with lubuntu;on this system i have mysql server mod_mono and altwfc server
i have downloaded the pkmnFondation i compiled all whit my server datas;i  copied database.sql to vmware and i run mysql -u myuser -p < database.sql mydatabase
aftee i run veekumimport and import database.
but i i run gts on iis debug or o n mod_mod i get an error regarding pkmn base stats.
i have to run only gts or gts and web?
And how set global terminal ip.

**Comment by PokeAcer549** [comment]
you need to publish the gts project (build/publish), make sure you changed DB stuff in all of the .config files, and you won't need to setup the ip, as *.nintendowifi.net is set to your server. But you'll need to set *.nintendo.co.jp to it aswell. Google 'dnsmasq adding wildcard domain'
You will also need wine to run the battle video server.

**Comment by andromeda01** [comment]
thank;
for base stats error i have resolved renaming the mysql table from stats to Stats.
i have builded gts and hosted on my mod _mono server,but if i go on my server ip:8080 (port how is hosted) i get error directory or dependecies not found;
if i run globalterminal on wine i get force close i have installed .net 2.0 which wine required at frist lunch,but still not work.
how run altwfc server on windows?
can anyone tell me how setup and send me a precompiled altwfc windows server (because my vs2012 can't compile pyproj)?

**Comment by PokeAcer549** [comment]
You need to install python and Twisted to run the scripts.

----- Reply message -----

**Comment by andromeda01** [comment]
whic script?

**Comment by PokeAcer549** [comment]
*facepalm*YOU CAN DOWNLOAD AltWFC PRECOMPILED FROM THE CODE PAGE

----- Reply message -----

**Comment by andromeda01** [comment]
if i run python altwfc script i have to set a dsn sever?
can post the link because i don't find it.

**Comment by PokeAcer549** [comment]
DNS* and yes, you need a DNS server.
IMO just setup a linux server, they're free to setup and easy.
Also AFAIK you can't run pkmnFoundations and AltWFC on same machine due to port conflicts.

**Comment by andromeda01** [comment]
tanks
i have iis express is good for gts server
what port must be gts server

**Comment by PokeAcer549** [comment]
80.

**Comment by andromeda01** [comment]
now i have lubuntu whit altwfc on lan ip 192.168.1.68 and my windows on 192.168.1.67 with gts on iis express and global terminal.
i have to configure dnsmasq to add wildcatd domaing for *.nintendo.co.jp to redirect to windows ?i have to configure only *.nintendo.co.jp or other dns
