### ISSUE TITLE
Problem connecting to the server (Pokemon Heart Gold) (Server:beanjr-fi)

### ISSUE THREAD

**Issue by nionios02** [mm201/pkmn-classic-framework#16]
So as the title says i can't contact to the server and keep getting 51200 errors.So my thought is that no one is online at the moment at pokemon heart gold.I also want to add is that i have registered my mac address to beanjr-fi and got accepted. I use my wifi hotspot from my phone becuase my router is with wpa password and ds can't connect to these routers. Well if someone could tell me if they can connect to the server with pokemon heart gold then the problem is my router.I want to try with other games like pokemon black . I'll appreciate any help !

**Comment by mm201** [comment]
Beanjr-fi isn't supported and never will be.

(There are programming assumptions made in the Pokémon games which break down when more than one server is involved. Let's leave it at that.)
