### ISSUE TITLE
New issues with install

### ISSUE THREAD

**Issue by PokeAcer549** [mm201/pkmn-classic-framework#17]
Hey @mm201 
I have an issue with IIS - for some reason, it only works when I try  http://<ip>/pokemondpds.ashx/... and not <ip>/pokemondpds/...

**Comment by mm201** [comment]
Is `RAMMFAR` enabled?

    <system.webServer>
        <modules runAllManagedModulesForAllRequests="true" />
    </system.webServer>

**Comment by PokeAcer549** [comment]
@Ciapa1 fixed this; one must manually select ASP.NET 4 because the Default AppPool is buggy.
