### ISSUE TITLE
Running from emulator

### ISSUE THREAD

**Issue by sebasgarcep** [mm201/pkmn-classic-framework#18]
I'm using a modded version of desmume with wi-fi capabilities. I patched the game with the given program in the instructions and then tried connecting to softAP, just like guides tell me, but I have been unable to get a connection. Is there any tested method for running the game from an emulator and connecting to the game servers? Or do we have to fork desmume to obtain this kind of  functionality?

**Comment by PokeAcer549** [comment]
Well, WiFi DeSMuME is not supported by the devs of DeSMuME or AltWFC..

**Comment by mm201** [comment]
You need to use a [custom build of Desmume](https://github.com/icedream/desmume). You may still encounter issues which I can't really help with.

**Comment by sebasgarcep** [comment]
Thanks very much! :) :+1:
