### ISSUE TITLE
'Bad Request'

### ISSUE THREAD

**Issue by PokeAcer549** [mm201/pkmn-classic-framework#19]
Hi,
my game sends a request like so:
http://gamestats2.gs.nintendowifi.net/pokemondpds/worldexchange/info.asp?pid=21296&hash=fc4c546e3b0cd442a56b7066e166e4a5c6b0df90&data=Sjssnn8KCZ4=

And I always get "Bad Request"
I never used to get this - I'm using the latest.
Thanks,
Poke

**Comment by mm201** [comment]
I'm not seeing anything in my logs. Are you using the production server or a private one?

**Comment by mm201** [comment]
To get you started, the only thing that request does is update a "last active" timestamp on your profile record in the database.

**Comment by PokeAcer549** [comment]
It's a private server.
As it's on Linux, all I done was edit the DB for pokemon_form_stats to pokemon_form_Stats.

**Comment by mm201** [comment]
Check that all the columns in `GtsProfiles4` other than `pid`, `TimeAdded`, and `TimeUpdated` allow nulls.

**Comment by mm201** [comment]
And sorry about the capitalization of table names. OSX is perfectly happy with it... This is something I'm in the process of changing.

**Comment by PokeAcer549** [comment]
It's fine, don't worry about doing it - Just remember not every OS likes them :P

**Comment by PokeAcer549** [comment]
They all allow nulls. http://prntscr.com/8ottk5
It seems like the script iself is refusing, yet there's a 500 in my logs from the 3DS doing it.

(127.0.0.1 occurs because I use SSH Tunnel to access it)

**Comment by PokeAcer549** [comment]
@mm201 any ideas?

**Comment by PokeAcer549** [comment]
.................................

**Comment by PokeAcer549** [comment]
@mm201 I done a packet dump, here's the 500 response I get from Mono:
http://prntscr.com/8pte7h

**Comment by mm201** [comment]
Now that's interesting. The crash is in the GamestatsBase library. Could you provide the request data?

**Comment by PokeAcer549** [comment]
What do you mean by request data?

**Comment by PokeAcer549** [comment]
Do you mean packet dump?

**Comment by PokeAcer549** [comment]
If you mean by what I request:


86.145.181.49 - - [10/Oct/2015:15:15:16 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:15:15:16 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296&hash=7733e60db6ef9dc5ed00ba75aa55c0173bd8f5d4&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:15:16:24 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:15:16:24 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296&hash=24f8b76ecfb596a34de599e39ea226a5f682551d&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:15:43:16 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:15:43:17 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296&hash=d80278b66d6ff63f907a2276739ff4e0320ceee3&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:18:48:39 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:18:48:42 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296&hash=769910e243af17e4ba534de524c5aaffcf76b68d&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:19:28:06 +0200] "GET /pokemondpds/battletower/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:19:28:08 +0200] "GET /pokemondpds/battletower/info.asp?pid=21296&hash=9f2ad5949c69d4a8daadbea7df6e396713c12f31&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:19:32:01 +0200] "GET /pokemondpds/battletower/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:19:32:03 +0200] "GET /pokemondpds/battletower/info.asp?pid=21296&hash=11eb83b98f81780c5aed440e37c74a1859fc3dbc&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"

**Comment by PokeAcer549** [comment]
I've just added you on Skype, so we could continue ourdiscussion there.

**Comment by mm201** [comment]
Is the setProfile.asp request succeeding?

**Comment by PokeAcer549** [comment]
There's no setProfile.asp request at all.

**Comment by PokeAcer549** [comment]
Another question - why not consider porting this to PHP?

**Comment by PokeAcer549** [comment]
Question: Any fixes for mono yet?
