### ISSUE TITLE
Out Of Bounds

### ISSUE THREAD

**Issue by PokeAcer549** [mm201/pkmn-classic-framework#20]
Hi @mm201,
I found out why the 500 occurs - http://prntscr.com/8pte7h
It does this:

86.145.181.49 - - [10/Oct/2015:18:48:39 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:18:48:42 +0200] "GET /pokemondpds/worldexchange/info.asp?pid=21296&hash=769910e243af17e4ba534de524c5aaffcf76b68d&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"

It also occurs in BattleTower:

86.145.181.49 - - [10/Oct/2015:19:28:06 +0200] "GET /pokemondpds/battletower/info.asp?pid=21296 HTTP/1.1" 200 285 "-" "GameSpyHTTP/1.0"
86.145.181.49 - - [10/Oct/2015:19:28:08 +0200] "GET /pokemondpds/battletower/info.asp?pid=21296&hash=9f2ad5949c69d4a8daadbea7df6e396713c12f31&data=Sjssnn8KCZ4= HTTP/1.1" 500 5017 "-" "GameSpyHTTP/1.0"

This is on a private server.

**Comment by carlosenam** [comment]
which distro you have?

**Comment by PokeAcer549** [comment]
This was on ubuntu using mono; mm201 has told me that this doesn't work using mono, so now I just ProxyPass and ProxyPassReverse to a Windows server running it.

**Comment by carlosenam** [comment]
Man I have a pkmnfoundations server running on linux(Apache + mono) and I have access to GTS

**Comment by PokeAcer549** [comment]
Odd. I've tried, and I never was able to make mono work with it. You should write exactly what you done as a wiki page.

**Comment by carlosenam** [comment]
Yeah, but I want to make a youtube video.

**Comment by PokeAcer549** [comment]
Then do that. It'd be very helpful for some of us :P

**Comment by celorodovalho** [comment]
@carlosenam Can you help me?
