### ISSUE TITLE
Error 20100

### ISSUE THREAD

**Issue by henias** [mm201/pkmn-classic-framework#21]
Hi!
I play Pokemon White 2 Europe Version on 3ds xl. Game was bought after official servers was down, so I couldn't  even reach Nintendo WFC menu before. Now with the WFCreplay and NoSSL codes finally i get into that. According to altWFC wiki, I Should go to options menu and erase NWFC configuration, what I could not do, couse erase option was shadowed, and actually there was nothing to erase. then go to Nintendo WiFi Connection Setting and setup connection with 104.131.93.87 DNS adress for both Primary and Secondary. Firstly i couldn't even save those settings, but then I read about port forwarding so I opened given TCP ports, but don't know how to allow all traffic to all destinations in UDP, so maybe problem is there, but offcial Nintendo page shows that everything should be fine. Ok, going to end this story. Finally i could save connection settings, and even tested it. This test shows that connection has been established. Then I continued my game i tried to connect with Nintendo WiFi Club (others also) in Pokemon Center and game shows well known error(for me) 20100. My suspicions goes to two thing. First is wrong AR Code, couse I have european version of PKMN White 2 cartridge, but found only Code for USA ver. and second maybe those UDP ports forwarding. Sorry for my English;)

**Comment by PokeAcer549** [comment]
IIRC, Pokemon White (2) and Black (2) are the same ROM for English in US and EU. Perhaps download an EU ROM and then make a code for it?
