### ISSUE TITLE
Is Wifi Club Trade enabled?

### ISSUE THREAD

**Issue by carlosenam** [mm201/pkmn-classic-framework#22]
I installed a pkmnfoundations (GTS) server with an AltWFC in a Linux Host. I tried to trade pokemon throught Club Wifi and Desmume shows me error 80430, My question is: Is wifi club implemented in a pkmnfoundations server?

thanks

**Comment by PokeAcer549** [comment]
80430 shouldn't have anything to do with it


Sent from Outlook Mobile






On Sat, Jan 16, 2016 at 1:02 PM -0800, "carlosenam" <notifications@github.com> wrote:





I installed a pkmnfoundations (GTS) server with an AltWFC in a Linux Host I tried to trade pokemon throught Club Wifi and Desmume shows me error 80430, My question is: Is wifi club implemented in a pkmnfoundations server?


thanks

---
Reply to this email directly or view it on GitHub:
https://github.com/mm201/pkmn-classic-framework/issues/22

**Comment by carlosenam** [comment]
Hi PokeAcer549 and thanks for the response. Then Wifi Club trade is implemented in a pkmnFoundations server?. if it is, I maybe made mistakes in the installation

**Comment by PokeAcer549** [comment]
Trading inside WiFi club uses AltWFC entirely for matchmaking, therefore has nothing to do with pkmn-classic-framework

**Comment by carlosenam** [comment]
I see, then I have asked in the wrong place
