### ISSUE TITLE
How to configure the DNS?

### ISSUE THREAD

**Issue by DracoMilesX** [mm201/pkmn-classic-framework#26]
I am getting the following error:

```
Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'PkmnFoundations.Web.controls.DnsAddress'.

Source Error: 


Line 1:  <%@ Control Language="C#" AutoEventWireup="true" CodeBehind="DnsAddress.ascx.cs" Inherits="PkmnFoundations.Web.controls.DnsAddress" %>
Line 2:  
Line 3:  127.0.0.1

Source File: /controls/DnsAddress.ascx    Line: 1 
```

How do I configure the DNS properly to work? I have tried adding the 2 websites to my windows host file but still got the same error.

If some one can tell me what to do or what to add to dnsmasq that would be great.

**Comment by mm201** [comment]
First of all, you're running the website when you probably want to run the gamestats server. Try the GTS project. And you need to use web deploy to "compile" the site into a state which ASP.NET will understand. You need Visual Studio or MonoDevelop for this.

**Comment by DracoMilesX** [comment]
Yes I have compiled and published both the gamestats server and website. This message comes indeed from the website. The Gamestats server works I guess it redirects me to a blanco webpage

**Comment by DracoMilesX** [comment]
Well I managed to get the website working as well.

Now I only remain with the issue that when I connect to the server that I get disconnected by GTS itself.
