### ISSUE TITLE
Friend code exchange

### ISSUE THREAD

**Issue by MiLeG** [mm201/pkmn-classic-framework#27]
Hey folks, keep up the good work! I would love a friend code exchange just to see who is still actively playing on the server. My  White 2 FC: 2534 0310 7320

**Comment by PokeAcer549** [comment]
Such an idea isn't good for an ISSUES page. Perhaps some sort of IRC chat could be used (*cough* #altwfc on Rizon *cough*), or a Discord?

**Comment by mm201** [comment]
I'm duping this to https://github.com/mm201/pkmn-classic-framework/issues/23 where they're asking for a way to communicate/share friend codes.

And yes, the server's still pretty active.
