### ISSUE TITLE
cant trade or battle pokemon SS

### ISSUE THREAD

**Issue by herculys** [mm201/pkmn-classic-framework#28]
i can get both accounts online, but when i go to trade or battle one lost conection with server.
![3](https://cloud.githubusercontent.com/assets/8635798/17273518/780c81ce-568d-11e6-8f8c-24d4fc11a3cf.jpg)

i tried to create a serve to check if was latency ping the problem, but seems like to be same disconection.
![2](https://cloud.githubusercontent.com/assets/8635798/17273517/780ab84e-568d-11e6-88fc-e135abcd5745.jpg)

in the compactibily list says that plaza and trainer is not implemented.
https://github.com/polaris-/dwc_network_server_emulator/wiki/Compatibility

Pokemon classics said on twitter that plaza does not work
https://twitter.com/pcnstatus/status/696731053512331264

i tried Union Room
but one character cant see the other, (ps. i got ids registred on Pal Pad of both and one can see the other inside wi-fi club)

so if nothing looks like to work, how i do trades and battles in pokemon SoulSilver and HeartGold
my twitter for contact: @Herculyys

**Comment by PokeAcer549** [comment]
You can't use DeSMuME. It doesn't work because of issues with emulation, aswell as some issues with searching of users.

**Comment by herculys** [comment]
so what pokemon can i play online with desmume?

**Comment by PokeAcer549** [comment]
None. Buy a DS.

**Comment by herculys** [comment]
i can't

**Comment by PokeAcer549** [comment]
Then don't play Pokemon, or learn how to fix DeSMuME and WiFi code :stuck_out_tongue:

**Comment by herculys** [comment]
i cant fix desmume, i dont know and i dont have acess x;x

**Comment by PokeAcer549** [comment]
So buy a DS somehow. It's simple
@mm201 you can shut this down now :P
