### ISSUE TITLE
Pokemon Black 2 not working on DeSmuMe

### ISSUE THREAD

**Issue by herculys** [mm201/pkmn-classic-framework#29]
like tittle said got conection with server ok, when try to go into GTS, and start try conection with "Nintendo WFC" (we know that is the pkm foundation server) i just get errors.
ps. room patched with WfcPatcher1.6

so for me seems like that none of pokemons games work online to trade or battle.

**Comment by PokeAcer549** [comment]
AS I SAID IN THE PREVIOUS ISSUE, IT WILL ERROR OUT ON DeSMuME.

**Comment by herculys** [comment]
man please................
there are people that got it working on DeSmuMe, just SHUT UP...
https://www.youtube.com/watch?v=_UzasCldaek
this guy made this video 2 days ago.

**Comment by herculys** [comment]
i just got it, hold it dude...
https://www.youtube.com/watch?v=urQxglHs7vc

**Comment by PokeAcer549** [comment]
How about you don't tell me to shut up, as I've actually worked with the servers and know that desyncing occurs? If they have it working, they've probably edited it in some format, or they're not doing it how you are, SIMPLE.

**Comment by herculys** [comment]
well, you started using caps and telling me to buy a ds, so sorry but you started.

**Comment by mm201** [comment]
This project handles GTS and Global Terminal (eg. battle videos), not PvP trading/battling. You're looking for [altwfc](https://github.com/polaris-/dwc_network_server_emulator). Additionally, the problem you're describing is with [Desmume](https://github.com/icedream/desmume)'s netcode, not the servers, which work just fine with the actual DS.
