### ISSUE TITLE
Creating a pkmnFoundations server error

### ISSUE THREAD

**Issue by gokudp** [mm201/pkmn-classic-framework#30]
error on visual studio
C:\Users\xsamp\Desktop\pkmn-classic-framework-master\GamestatsBase\GamestatsBase\GamestatsBase.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\xsamp\Desktop\pkmn-classic-framework-master\GamestatsBase\GamestatsBase\GamestatsBase.csproj'.  C:\Users\xsamp\Desktop\pkmn-classic-framework-master\GamestatsBase\GamestatsBase\GamestatsBase.csproj

**Comment by PokeAcer549** [comment]
`git clone --depth 1 https://github.com/mm201/pkmn-classic-framework`

Or download GameStatsBase and put it in the GamestatsBase folder

**Comment by gokudp** [comment]
got it, thanks
i'm going to last instruction:
GlobalTerminalService>bin>debug>GlobalTerminalService.exe (Battle Video Server) and set gamestats2.gs.nintendowifi.net and pkgdsprod.nintendo.co.jp to your IP (external if a public server, Internal if LAN only).

![1](https://cloud.githubusercontent.com/assets/20784731/17337543/8235323a-58b9-11e6-9d95-cda3193644e6.jpg)

got this x.509 certificate not found, and i dont know what is.
and how i set gamestats2.gs.nintendowifi.net and pkgdsprod.nintendo.co.jp to my IP?

**Comment by PokeAcer549** [comment]
Ignore the X.509 cert error, it doesnt affect your usage of the game, and you need to set it in your DNS server. I also recommend against using Ubuntu, as mono has issues with the server (not the server you're using in the screenshot, but the regular Global Terminal server)

**Comment by gokudp** [comment]
there are no instrunctions to setup dwc_network_server_emulator on windows, and we need it right?

**Comment by PokeAcer549** [comment]
Yes, but in practice @mm201 runs his server seperately and AltWFC merely forwards to it; you can setup AltWFC with Windows, just copy the v-hosts into your XAMPP apache directory, enable them in the conf file and restart, and then just get the required Python packages.

**Comment by gokudp** [comment]
thanks i got sucess installing python packages, im stuck in copy v-hosts into apache.
are you talking about these files:?
gamestats.gs.nintendowifi.net.conf
gamestats2.gs.nintendowifi.net.conf
nas-naswii-dls1-conntest.nintendowifi.net.conf
sake.gs.nintendowifi.net.conf

where i put it?
C:\xampp\apache\conf
or
C:\xampp\apache\conf\extra
or
C:\xampp\apache\conf\original\extra

and how to enable them in conf file?

**Comment by PokeAcer549** [comment]
http://itridersblog.com/blog/setup-virtual-host-xampp/ for VHosts,
and the FQDN thing can be ignored :P

**Comment by gokudp** [comment]
i did this with my vhost file:
`<VirtualHost *:80>
DocumentRoot "C:\xampp\htdocs"
ServerName localhost
</VirtualHost>

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName gamestats.gs.nintendowifi.net
        ServerAlias "gamestats.gs.nintendowifi.net, gamestats.gs.nintendowifi.net"
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:9002/
        ProxyPassReverse / http://127.0.0.1:9002/
</VirtualHost>

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName gamestats2.gs.nintendowifi.net
        ServerAlias "gamestats2.gs.nintendowifi.net, gamestats2.gs.nintendowifi.net"
 
        ProxyPreserveHost On
 
        ProxyPass / http://127.0.0.1:9002/
        ProxyPassReverse / http://127.0.0.1:9002/
</VirtualHost>

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName naswii.nintendowifi.net
        ServerAlias "naswii.nintendowifi.net, naswii.nintendowifi.net"
        ServerAlias "nas.nintendowifi.net"
        ServerAlias "nas.nintendowifi.net, nas.nintendowifi.net"
        ServerAlias "dls1.nintendowifi.net"
        ServerAlias "dls1.nintendowifi.net, dls1.nintendowifi.net"
        ServerAlias "conntest.nintendowifi.net"
        ServerAlias "conntest.nintendowifi.net, conntest.nintendowifi.net"
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:9000/
        ProxyPassReverse / http://127.0.0.1:9000/
</VirtualHost>


<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName sake.gs.nintendowifi.net
        ServerAlias sake.gs.nintendowifi.net *.sake.gs.nintendowifi.net
        ServerAlias secure.sake.gs.nintendowifi.net
        ServerAlias secure.sake.gs.nintendowifi.net *.secure.sake.gs.nintendowifi.net
 
        ProxyPass / http://127.0.0.1:8000/
 
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`

and got this error trying start apache
09:15:16  [Apache] 	Error: Apache shutdown unexpectedly.
09:15:16  [Apache] 	This may be due to a blocked port, missing dependencies, 
09:15:16  [Apache] 	improper privileges, a crash, or a shutdown by another method.
09:15:16  [Apache] 	Press the Logs button to view error logs and check
09:15:16  [Apache] 	the Windows Event Viewer for more clues
09:15:16  [Apache] 	If you need more help, copy and post this
09:15:16  [Apache] 	entire log window on the forums

**Comment by gokudp** [comment]
well i copied all .conf files from dwc_network_server_emulator-master\tools\apache-hosts
to C:\xampp\apache\conf\extra

do you know how to enable them like in linux was
`sudo a2ensite`

how i enable them here?

**Comment by mm201** [comment]
I can probably fix mod_mono issues pretty easily if there's interest.

**Comment by PokeAcer549** [comment]
IDK; Why users would need to build their own server makes no sense; if you want a pokemon trading facility you want it to be centralised :/

**Comment by gokudp** [comment]
for private trades, because wi-fi club or any other way does not work, so need to use GTS and i dont want to get hacked pokemons from others.

**Comment by PokeAcer549** [comment]
Private trades would work in WiFi club, and you can just check the Pokémon if you have the right packet dumping equipment

**Comment by mm201** [comment]
Wi-fi club does work, just not in emulators. If you need to trade over GTS, one effective strategy is to put up, e.g., a Magikarp but ask for Dialga. Then get the other guy to accept that trade. The other guy also puts up a Magikarp but asks for Palkia or whomever. Even if someone else fulfills your trade, free legendaries!

And with emulators, swapping save files is always an option.
