### ISSUE TITLE
How to forward from AltWFC > Pokémon Server?

### ISSUE THREAD

**Issue by trilleplay** [mm201/pkmn-classic-framework#31]
Can somebody tell me how to forward from AltWFC to Pkmn-classic-framework

**Comment by bankkopf** [comment]
Use your DNS to forward gamestats2.gs.nintendowifi.net and pkgdsprod.nintendo.co.jp to your altwfc server.

**Comment by PokeAcer549** [comment]
^ it's pretty much all you can do.

**Comment by cedianoost** [comment]
Also use the AR code for your game
