### ISSUE TITLE
Trainer Rankings (Pt/HG/SS) is not implemented

### ISSUE THREAD

**Issue by ghost** [mm201/pkmn-classic-framework#32]
On the production server, both "This week's rankings" aswell as "Last week's rankings" give 'an error has occured'

PCAP: https://download.rc24.xyz/dumps/trankings.pcap

**Comment by mm201** [comment]
I never got around to finishing this and it's not really a high priority. I thought there was already a todo issue but apparently not.

**Comment by InternalLoss** [comment]
afaik, other than 'full' Wi-Fi Plaza support (Which iirc is just the poll data), this is the only thing not currently working on Generation 4?

**Comment by mm201** [comment]
It's done! Thanks a bunch to @AdmiralCurtiss for their packet dumps which made this possible!

**Comment by AdmiralCurtiss** [comment]
Neat! Glad those dumps are still useful so many years later.
