### ISSUE TITLE
How pkmn-classic-framework is reading the AltWFC database?

### ISSUE THREAD

**Issue by celorodovalho** [mm201/pkmn-classic-framework#33]
I'm wondering to know, how pkmn-classic-framework is reading the AltWFC database?

Coz, I want to develop a "PHP version" of pkmn-classic-framework for linux/apache users.

**Comment by PokeAcer549** [comment]
IIRC it doesn't need to; it works fine when we use it through Wiimmfi.

**Comment by celorodovalho** [comment]
What this means?
How can I connect "pkmn-classic-framework" to "AltWFC"?

Att,

**Comment by PokeAcer549** [comment]
A) Don't do it on the production (public) server
B) you do it in DNS.

**Comment by mm201** [comment]
It doesn't. All the magic is done on the client in the most insecure way imaginable. (Which is why GTS spoofers were possible back in the day.)

A full php rewrite sounds like a very big job and that effort would be better spent porting it to mono/.net core IMO.

**Comment by celorodovalho** [comment]
Can I connect through WebSocket?

new WebSocket('ws://104.131.93.87') ??

What is the port?
I'm programmer, but I dont understand ASP well.
I want to connect to understand, then to dev a server with NODE.js (not PHP anymore).

**Comment by PokeAcer549** [comment]
Not how it works: The DS connects to the server over port 80 (it's ran on mm201's server, not the AltWFC production server; it's proxied)

**Comment by celorodovalho** [comment]
@PokeAcer549 Why so rude answer?
I'm trying to learn and possibly help you all.
This a "new world" to me, so a little patience is kind.

**Comment by PokeAcer549** [comment]
Not rude, just informative :wink:
