### ISSUE TITLE
AltWFC is down. 

### ISSUE THREAD

**Issue by celorodovalho** [mm201/pkmn-classic-framework#35]
Hi there. 
AltWFC server is down since December 7th. 
Can you help us with that? 

I know are distinct things, but maybe you know how to contact Nagato.

**Comment by PokeAcer549** [comment]
Contact him yourself? HGe's on IRC...

**Comment by celorodovalho** [comment]
I tried. He is never online and never answer.

**Comment by celorodovalho** [comment]
@AdmiralCurtiss @PokeAcer549 @mm201 
Can you help with that please? The AltWFC official server must restart OR
help me with that issue: https://github.com/polaris-/dwc_network_server_emulator/issues/356#issuecomment-268221832
I'm getting Error 13274 when I connect on GTS in my own server (45.55.238.131).

**Comment by PokeAcer549** [comment]
...
A) I don't control AltWFC. B) Only Nagato can access the server.
Also, **do not use your own server with GTS.** That will be where your issue is.

**Comment by celorodovalho** [comment]
"do not use your own server with GTS"
Ok, if the official AltWFC was working.

I'm using a clean linux instalation.

**Comment by PokeAcer549** [comment]
If the official was working, then WHEE GOOD. But it isn't.
It's most likely PID overlap. You can't use it rn ;P

**Comment by mm201** [comment]
Wiimmfi is safe to use with GTS. Try that for the time being.

I can try to pester Nagato but I don't have any better contact with him than any of you do.
