### ISSUE TITLE
can't use mystery gift 

### ISSUE THREAD

**Issue by dmoeenm** [mm201/pkmn-classic-framework#37]
In pokemon diamond when i try to get a mystery gift via Nintendo wfc it will give me an error as it starts searching  and the error is 31020 right after that when i try it again the connection bars disappear and it freezes in the middle of its search im using a ds and an action replay  and all my other ds pokemon games connection and work with and can receive  mystery gifts

**Comment by ductator** [comment]
Mystery gifts are handled by dwc_network_server_emulator

**Comment by dmoeenm** [comment]
Oh my bad
