### ISSUE TITLE
[Not related to code] Server down for pkmn-classic?

### ISSUE THREAD

**Issue by PokeAcer** [mm201/pkmn-classic-framework#40]
It seems PKMNClassic's IP is not accessable; I tried connecting for Wiimmfi and via cURL and both 404.

**Comment by mm201** [comment]
I'm able to access http://pkmnclassic.net just fine. I'll do more testing when I have a computer.

**Comment by PokeAcer** [comment]
I can access the site, however when cURLing `curl -H "gamestats2.gs.nintendowifi.net" 191.236.98.208/pokemondpds/worldexchange/info.asp` I get this
![Imgur](https://i.imgur.com/O5Q9fms.png)
