### ISSUE TITLE
Error 52000, 23502 or 71010 in the WIFI club

### ISSUE THREAD

**Issue by SixtyHertzGD** [mm201/pkmn-classic-framework#41]
Hello everyone, i tried to connect with a friend with the WIFI club but i got the Error code 52000, 23502 or 71010 everytime i try to connect. My connection is pretty good and i can connect with the same connection, the same game, the same console, the same FC etc to GTS, and other WIFI stuff.

**Comment by PokeAcer** [comment]
That's not in the scope of pkmn-classic-framework.
