### ISSUE TITLE
help! build errors!

### ISSUE THREAD

**Issue by lryx1993** [mm201/pkmn-classic-framework#45]
![image](https://user-images.githubusercontent.com/30574182/29597595-3c4e115c-87f6-11e7-8dcd-a39b75d4c495.png)
![image](https://user-images.githubusercontent.com/30574182/29597604-4445f23a-87f6-11e7-976b-eeeeeb63c970.png)
There are always build errors, what should i do?

**Comment by mm201** [comment]
Try restoring the Nuget packages.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore

**Comment by mm201** [comment]
Works for me on a fresh environment. I'll go ahead and close this.
