### ISSUE TITLE
GTS Search potentially borked?

### ISSUE THREAD

**Issue by pokeacer** [mm201/pkmn-classic-framework#48]
When searching on http://pkmnclassic.net/gts/ for Gen V Pokémon, none are shown. However, when you search on Gen IV on the site, Victini (a Gen V only!) shows up; it seems as though it's almost slightly messed up??

Furthermore, perhaps Gen IV/V interoperability could occur where you could trade between the two using GTS (So all the pokemon in Gen IV's GTS are viewable in Gen V, and all non-Unova pokemon in V's shows in Gen IV's)

**Comment by mm201** [comment]
That Victini looks like it was put there by a hacker. Unfortunately, the GTS protocol is very trusting of clients. I've been meaning to add improved validation (https://github.com/mm201/pkmn-classic-framework/issues/3) for a while now and it's first on my list when I get back to the project.

The dropdown showing Gen5 pokemon in all circumstances was a design compromise I made to make the coding of it simpler. I could fix it with a few lines of Javascript but I never deemed it important enough.

Closing this as a dupe.
