### ISSUE TITLE
[Question] Does this project support Wonder Cards?

### ISSUE THREAD

**Issue by SunFlea** [mm201/pkmn-classic-framework#52]
Before I spend awhile setting everything up: I'd like to know if this project supports serving event Wonder Cards to 4th gen games?

**Comment by SunFlea** [comment]
![oak s letter](https://user-images.githubusercontent.com/18683240/39252673-c8237312-486b-11e8-9812-ac601343bfd4.png)
![members card](https://user-images.githubusercontent.com/18683240/39252677-cac7cb18-486b-11e8-9f0e-bf02cfcc7b14.png)
![secret key](https://user-images.githubusercontent.com/18683240/39252680-cbfb93d4-486b-11e8-9dff-3c520cdf213e.png)

**Comment by mm201** [comment]
Altfwc currently provides wondercards, but I do have interest in implementing them myself to learn more about how they work.
