### ISSUE TITLE
any chance to see random uploaded battle ID videos?

### ISSUE THREAD

**Issue by cotodevel** [mm201/pkmn-classic-framework#53]
I think some users might disagree, but hell, I really like the idea of watching random battle videos from my DS. Since people rarely play Platinum as, say 9 years ago...

Is there any possibility to at least upload a randomized battle video ID here: http://pkmnclassic.net/battlevideo/ so I could watch them directly from Platinum (EUR) version?

**Comment by cotodevel** [comment]
rip

**Comment by mm201** [comment]
in pieces
