### ISSUE TITLE
Server offline or under maintenance?

### ISSUE THREAD

**Issue by Basinator89** [mm201/pkmn-classic-framework#54]
A forums user tried to connect 5 days ago for the first time without any success. I didn't try myself, but I pinged >ping 104.131.93.87 and didn't receive a reply.

**Comment by mm201** [comment]
Digitalocean (where altwfc is hosted) and Azure (where PCN is hosted) don't route ICMP (ping) traffic so pings will fail. When I visit http://104.131.93.87:9001/ and http://pkmnclassic.net/ they both come up.

Altwfc is known to crash periodically. I wouldn't rule that out. Either way, not relevant to this project so I'll close this.

**Comment by Basinator89** [comment]
Ok, sorry for bringing it up. So server is running and should behave fine?

**Comment by mm201** [comment]
I can't test at the moment but everything appears fine.
