### ISSUE TITLE
Remove need for patching games.

### ISSUE THREAD

**Issue by shadowofdarkness** [mm201/pkmn-classic-framework#56]
Recently a flaw was found in how the NDS handles SSL and you no longer need to use AR to patch the game. Just a stock game with the custom DNS address.
Would you be willing to implement this advancement server side?

https://github.com/KaeruTeam/nds-constraint

**Comment by mm201** [comment]
I

Love

You!!

But do you remember IR-GTS and all the other fake GTSes from back in the day? They never required an SSL hack to function, and neither does PCN. As long as all the DNS entries are set up properly, it should just work.

But having the ability to bypass SSL will be invaluable for implementing [Game Sync](https://github.com/mm201/pkmn-classic-framework/issues/8)!

Is there a good place to discuss this further? AltWFC IRC perhaps?

**Comment by shadowofdarkness** [comment]
I'm just a end user that found out about that and did a quick test by grabbing a mystery gift from the test server so I know it works.
I'm not sure who to talk to about that other then probably the owner of that git repo.

**Comment by mm201** [comment]
I'll go ahead and close this since it isn't actually an issue or is covered by other issues. And I still love you!
