### ISSUE TITLE
[Potentially SSL again] Random Matchup free battles apparently not working

### ISSUE THREAD

**Issue by InternalLoss** [mm201/pkmn-classic-framework#61]
Again, another "might be Nintendo adding in SSL or it might be not working at all"; Random Matchup battles appear to be non-functional.

**Comment by mm201** [comment]
pkvldtprod is the anti-cheat server. It's used to prevent trading hacked pokemon to unsuspecting players or using them against them in battles. Random Matchup is dead for the same reason GTS is.
