### ISSUE TITLE
KWFC DNS doesn't work so great with other games

### ISSUE THREAD

**Issue by fancythedeveloper** [mm201/pkmn-classic-framework#62]
****PLEASE NOTE THIS POST IS FOR THE MAIN PKMNCLASSIC WEBSITE AND NOT THE GITHUB***

Is it possible you can the DNS from KaeruTeam's to RiiConnect24's?
RC24's is more popular, the DNS for it is 164.132.44.106.
IDK if the main DNS still works but still, RC24's is more popular.

**Comment by mm201** [comment]
Some stuff is configured incorrectly on that DNS server and some other things will eventually need to be changed as development progresses. Who should I contact to manage these changes?

**Comment by fancymelonub** [comment]
The RC24 team, who host the DNS. So you should contact Larsenv or KcrPL. And maybe Shutter.

**Comment by InternalLoss** [comment]
@larsenv or I can be contacted over Discord as usual for that DNS server :p

**Comment by InternalLoss** [comment]
the various problems mentioned in this issue should be fixed now; both DNSes should correctly work, and this can be closed.
