### ISSUE TITLE
PkmnClassicNetwork Domain Name

### ISSUE THREAD

**Issue by mikelan98** [mm201/pkmn-classic-framework#63]
I tried to reverse the DNS 178.62.43.212 to an address, but there are no matches. I'm a ROM hacker (and I'm planning to give support to PkmnClassicNetwork from my game) but I want to replace directly the domain names in the ROM, because too much players will not know how to set up DNS and that stuff. Could you tell me the domain name of the server and, for instance, where is the conntest.[?]/test.html page? If you want, this is my mail: mikelan98@gmail.com

Thanks!

**Comment by fancymelonub** [comment]
1. The Kaeru DNS is dead.
2. Just use RC24's DNS (164.132.44.106)
3. Dude, it's as simple as going into WFC Settings and setting up the DNS.

**Comment by mm201** [comment]
I don't recommend this approach. It's become the established norm that to get DSes online you do DNS spoofing. Having one game that works differently would only lead to problems and user annoyance.

Also, if you're doing a significant ROM hack, you may get caught up in anti-cheat. I would suggest running a private PCN instance specific to your hack if you get this far.
