### ISSUE TITLE
Error 52100 Pokemon Diamond

### ISSUE THREAD

**Issue by Kandy2a** [mm201/pkmn-classic-framework#68]
Hello,
I'm French and I tried to find a solution to my problem but I am at a standstill, so I allow myself to post my situation...
I tried to enter the DNS 178.62.43.212 of Poké Classic Network to connect to the Pokemon Diamond GTS. However, I have a concern that is probably related to my internet connection. I make a connection with my phone without a security password because I do not have a modem WEP key. When connecting from the game to the server, all the connection bars are green then disappear and turn red and the error message 52100 is displayed constantly ... I tried to do without and with the code of Action Replay DS(i) but the problem is still present.
Do I need to have a WEP key modem? Does the problem come from shutting down the server?

Thank you.

**Comment by hfc2x** [comment]
Make sure your secondary DNS is 1.1.1.1 or 8.8.8.8. The WEP key thing is not necessary, and I connect with my phone's hotspot, which is unsecured.

I also had a similar issue [here](https://github.com/barronwaffles/dwc_network_server_emulator/issues/521), and it got solved by deleting my console's WiFi information.
