### ISSUE TITLE
Hacked Pokémon in the GTS

### ISSUE THREAD

**Issue by hfc2x** [mm201/pkmn-classic-framework#69]
First of all, sorry if this is not the place for this, but I don't know if hackers can be reported or something like that at all. I know that in some games that use AltWfc, people can get reported and banned from certain games because of hacking or cheating, so might as well simply raise awareness.

There's this person who's been offering hacked Shiny Pokémon in the GTS that has 2 usernames. One is MAC (male), and the other is RACH (female), and both have a Trainer ID of 2002 and a Secret Trained ID of 2012. I know the Shiny Pokémon this person is putting up for offer are "technically legal", since they're being obtained through the [Cute Charm glitch](https://www.smogon.com/ingame/rng/dpphgss_rng_part5), but to obtain those exact Trainer ID and Secret ID in two separate save files, this person is clearly cheating.

I did some tests the other day and traded them some Pokémon to verify all this. This person is often asking for highly-leveled, hard-to-obtain Pokémon in exchange for these hacked shinies, and one of my trades involved raising a Flareon to over level 50, which was pretty time-consuming, so I suspect they're doing this so people do hard work for them, and I think that's really unfair.

I attach two of the Pokémon I've obtained from this person so anyone who can use Gen 4 PKM files can see this for themselves. These are in Gen 4 format, and are 136-byte unencrypted PKM files:

[Hacked shinies.zip](https://github.com/mm201/pkmn-classic-framework/files/3390432/Hacked.shinies.zip)

**Comment by mm201** [comment]
Unfortunately, cloning, RNG abuse, and trainer ID modification can't be proven in an automated way. For all other cheats, please see #3 . I will file an issue to remind myself to fast track the moderation system but I don't think this particular situation merits any action.

**Comment by hfc2x** [comment]
I think that if there are some things that can't be proven, like RNG manipulation, it's fair game I guess. However, at the very least, the Cute Charm abuse always yields the exact same results, because the PIDs of the Pokémon that are generated through the glitch are always those from the list. Preventing those specific PIDs (which are practically impossible to come across without blatant abuse) from being deposited into the GTS could mitigate that one.

The Cute Charm-abused shinies _always_, with _no exception_ have the following PIDs:
> 00000000
> 00000000
> 00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
