### ISSUE TITLE
Wrong Nature shown on website

### ISSUE THREAD

**Issue by phi1997** [mm201/pkmn-classic-framework#72]
I offered a Modest nature Elgyem with Synchronize on the GTS, but when I checked it for offer on the website, it showed up with a Gentle Nature. I do not know if this will effect anyone who attempts to trade for it.

**Comment by phi1997** [comment]
If it's relevant, I used an Everstone while breeding to make sure the Elgyem had a Modest nature

**Comment by mm201** [comment]
It means my documentation of the GenV format is wrong but no, the GTS is designed so that the server can be very dumb and this won’t have any effect on the Pokémon that’s sent through.

**Comment by mm201** [comment]
I have a prospective fix in place and many listed natures have changed. Can you confirm than an affected Pokémon now shows the correct nature?

**Comment by InternalLoss** [comment]
My Rash natured Azurill and Jolly Oshawott both shown correctly on site, so this seems to be fixed.
