### ISSUE TITLE
GTS Electrode in Gen 4

### ISSUE THREAD

**Issue by Angryxjohnny** [mm201/pkmn-classic-framework#75]
Currently there is an Electrorode I've been trying to trade with in the GTS from a trainer named ADAM. 

Here's a screenshot of the posting. Whenever I trade it kicks me off to the title screen! Afraid of being soft banned so only tried twice, but with same result.

**Comment by mm201** [comment]
Sounds like a mix of #3 and #70. I'll kick the electrode when I get the chance. Please see those two existing issues to continue discussion.
