### ISSUE TITLE
GTS "Deposit Pokemon" option is available when a Pokemon is already deposited.

### ISSUE THREAD

**Issue by camthesaxman** [mm201/pkmn-classic-framework#76]
With a Pokemon deposited in the GTS, the SUMMARY option shows up as expected. However, after viewing the summary and returning to the previous screen, the SUMMARY is replaced with DEPOSIT POKEMON, as if there was no Pokemon deposited. Attempting to deposit another Pokemon results in the player being disconnected from the GTS.

This was tested on Diamond version. It's unknown if other gen 4 games experience this.

Video demonstration here: https://drive.google.com/open?id=1VO_2vx4Biy0iQuvA9efXxoXQfSNoDx8G

**Comment by mm201** [comment]
This is a bug in the *game client*. It happened on the official GTS. I don't think there's any serverside cheese I can do to fix it. I think it's fixed in Platinum onward. (Or was that HGSS? I forget.)
