### ISSUE TITLE
Hello, would like to contribute. My proposal redesign of http://pkmnclassic.net website :)

### ISSUE THREAD

**Issue by lowlightdev** [mm201/pkmn-classic-framework#77]
**About**
Hi @mm201 ,
I really liked what you did with the classic pkmn network, good job :+1: . I just order my first DS(a childhood dream) :D and found out that Online Pokemon can still be played due to some work on the internet of some good people :)
I've looked over the project andd thought and wanted to offer my input if you need it. I could help with javascript as I'm a javascript developer(nodejs) and web development.

**Solution**
I've did a redesign of http://pkmnclassic.net/ website which can be viewed **[here http://pkmn.victorz.me](http://pkmn.victorz.me)**. 
- built it using VueJS, 
- used bootstrap.css and nes.css as design base css frameworks
- mobile supported
I'm not sure exactly how to integrate this work as I don't know any C and the app seems monolithic. If there is any other way to help integrate it I'd like to help if possible(btw vuejs can be removed if it's not needed but you like the design)

**Alternative solutions & suggestions**
- Maybe creating some API endpoints for the backend and that  can consumes and server the data ? don't know the consequence's of this and the implications,but the website could be decoupled and work more easly? just my 2 cents...
- Could also help maintain some non dev aspect things like upgrade social presence, maybe create a discord or keep up to date the twitter account etc
- i also would have some other ideas for the app if you'd like to hear :crossed_fingers: 

Best regards,
Zapo.

**Comment by mm201** [comment]
Hey

Thanks so much for your interest in this project! Unfortunately, as I currently have a rewrite of the site in progress using knockout.js and Web API, I have to respectfully decline.

The website already works independently and talks to the other services over local mariadb and a class library to provide data structures and OO pokedex. The main shortcoming is it was speedcoded in 2014 and is therefore very bare-bones, not responsive, dated, and full of unfinished ideas.

I certainly could use your help with social media presence and website content creation, e.g. tutorials, troubleshooting, and any other ideas. Contact me on Discord at mm201#9104 and we can discuss further.

**Comment by lowlightdev** [comment]
hey @mm201 will add you this weekend, maybe we can have a little chat :). I'll close this ticket for the time.

**Comment by lowlightdev** [comment]
Hey @mm201 i've added on github. I'm zapo :)
