### ISSUE TITLE
Battle video search type 254

### ISSUE THREAD

**Issue by mm201** [mm201/pkmn-classic-framework#9]
This is bugging me. In my logs, I have reports of players doing a battle video search with a type ID of 254. I don't know what this is. When I was recording traffic, I did all the searches and nothing like this came up, so I don't really know what to do with it.

What I've pieced together through logs is:
It can happen on Platinum and Heart Gold versions. Presumably Soul Silver too but it's not in my logs.
It can be combined with species searches.
It's the first/only thing lots of players do so it might become a default when the conditions to unlock it are met.

Originally, this search always returned 0 results on my server. Recently, I've changed it so that it will generate an error message, "there was a problem with your search." If you see this error message, please tell me what you did to cause it.

**Comment by mm201** [comment]
Based on more logs, I think this is a "latest 30" search coming from certain games. Players who do this search never try to do a normal latest 30 search, but some of them try to combine it with other filters like species, to no avail.

I still don't know why it's generated by some games and not others. It doesn't seem linked to version or language.

**Comment by InternalLoss** [comment]
Seems like 254 is for when a user performs a search (ex "search for Eevee and no set battle mode and no location"), but they **have not** cleared Elite Four and thus don't have Battle Frontier - this explains why this can only be found in Platinum/HG/SS

**Comment by mm201** [comment]
That makes a lot of sense; thank you!
