### ISSUE TITLE
Battle Video Rankings should have a reasonable sort

### ISSUE THREAD

**Issue by mm201** [mm201/pkmn-classic-framework#91]
The battle video rankings is supposed to be a top list of the most "popular" battle videos. But popular according to what/whom? Right now I sort them by battle tower streak length which is kind of cool but not really ideal and it doesn't work with Colosseum videos.

We could sort them by number of times viewed, but that's kind of self-reinforcing. We could also use a more complicated heuristic that takes age, popularity, and other things into account. But what we do right now clearly isn't good enough.

If anyone knows how the original server sorted these, that would be very welcome information.

**Comment by 1creeperbomb** [comment]
Don't know how Nintendo did it, but I vaguely remember the popular battle videos changing either daily or weekly.

Maybe you could do something similar to "hot" on reddit where posts are sorted by most upvotes over time. In this case it would be a most views over time ratio.

**Comment by mm201** [comment]
Weekly makes sense. The feature is in a similar place as trainer rankings, which updates weekly.
